default:
  image: "nixos/nix"
  tags:
    - docker

stages:
  - build
  - check

variables:
  flags: "--extra-experimental-features nix-command --extra-experimental-features flakes"

before_script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use dit356

notification-service:
  stage: build
  script:
    - nix ${flags} build .#notification-service && cachix push dit356 result

availability-service:
  stage: build
  script:
    - nix ${flags} build .#availability-service && cachix push dit356 result

booking-service:
  stage: build
  script:
    - nix ${flags} build .#booking-service && cachix push dit356 result

logging-service:
  stage: build
  script: nix ${flags} build .#logging-service && cachix push dit356 result

check-formatting:
  stage: check
  script: nix ${flags} flake check
  needs: []
